/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package serverForm;

import configuration.Configuration;
import javax.swing.JOptionPane;

/**
 *
 * @author milan
 */
public class KonfiguracijaForm extends javax.swing.JFrame {

    /**
     * Creates new form KonfiguracijaForm
     */
    private Configuration config;
    public KonfiguracijaForm() {
        initComponents();
        setLocationRelativeTo(null);
        config = Configuration.getInstance();
        fillFields();
        setFieldsEnabled(false);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldURL = new javax.swing.JTextField();
        jTextFieldUser = new javax.swing.JTextField();
        jTextFieldPort = new javax.swing.JTextField();
        jPasswordField = new javax.swing.JPasswordField();
        jLabelURL = new javax.swing.JLabel();
        jLabelUser = new javax.swing.JLabel();
        jLabelPass = new javax.swing.JLabel();
        jLabelPort = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        JButtonChange = new javax.swing.JButton();
        jButtonSave = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Konfiguracija");
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("URL:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 25, 120, 20));

        jLabel2.setText("Username:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 60, 120, 20));

        jLabel3.setText("Password:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 95, 120, 20));

        jLabel4.setText("Port:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 130, 120, 20));

        jTextFieldURL.setBorder(null);
        jPanel1.add(jTextFieldURL, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 25, 209, 20));

        jTextFieldUser.setBorder(null);
        jPanel1.add(jTextFieldUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 209, 20));

        jTextFieldPort.setBorder(null);
        jPanel1.add(jTextFieldPort, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 209, 20));

        jPasswordField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordFieldActionPerformed(evt);
            }
        });
        jPanel1.add(jPasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 95, 209, 20));

        jLabelURL.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabelURL.setForeground(new java.awt.Color(255, 0, 0));
        jLabelURL.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel1.add(jLabelURL, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 45, 209, 15));

        jLabelUser.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabelUser.setForeground(new java.awt.Color(255, 0, 0));
        jLabelUser.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel1.add(jLabelUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 209, 15));

        jLabelPass.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabelPass.setForeground(new java.awt.Color(255, 0, 0));
        jLabelPass.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel1.add(jLabelPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 115, 209, 15));

        jLabelPort.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabelPort.setForeground(new java.awt.Color(255, 0, 0));
        jLabelPort.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel1.add(jLabelPort, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, 209, 15));

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        JButtonChange.setText("Izmeni");
        JButtonChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonChangeActionPerformed(evt);
            }
        });

        jButtonSave.setText("Sačuvaj");
        jButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(JButtonChange, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonSave, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JButtonChange)
                    .addComponent(jButtonSave))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 434, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveActionPerformed
        String url = jTextFieldURL.getText();
        String username = jTextFieldUser.getText();
        String pass = new String(jPasswordField.getPassword());
        String port = jTextFieldPort.getText();

        if (!valid(url, username, pass, port)) {
           // JOptionPane.showMessageDialog(this, "Greška prilikom unošenja podataka.", "Greška", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if(!config.doesExist())
            config.createFile();
        config.setProperty("db_url", url);
        config.setProperty("db_user", username);
        config.setProperty("db_password", pass);
        config.setProperty("port", port);

        JOptionPane.showMessageDialog(this, "Konfiguracija sacuvana uspesno, restartujte server!", "Obaveštenje", JOptionPane.INFORMATION_MESSAGE);
        this.dispose();

    }//GEN-LAST:event_jButtonSaveActionPerformed

    private void jPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordFieldActionPerformed

    private void JButtonChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonChangeActionPerformed
        setFieldsEnabled(true);
        JButtonChange.setEnabled(false);
    }//GEN-LAST:event_JButtonChangeActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JButtonChange;
    private javax.swing.JButton jButtonSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelPass;
    private javax.swing.JLabel jLabelPort;
    private javax.swing.JLabel jLabelURL;
    private javax.swing.JLabel jLabelUser;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField;
    private javax.swing.JTextField jTextFieldPort;
    private javax.swing.JTextField jTextFieldURL;
    private javax.swing.JTextField jTextFieldUser;
    // End of variables declaration//GEN-END:variables

    private boolean valid(String url, String username, String pass, String port) {
        boolean isValid = true;
        
        jLabelPass.setText("");
        jLabelURL.setText("");
        jLabelUser.setText("");
        jLabelPort.setText("");
        
        if (url.isEmpty() || !url.matches("^jdbc:mysql://localhost:\\d{1,5}/[a-zA-Z_][a-zA-Z0-9_]*$")) {
            jLabelURL.setText("Neispravan URL!");
            isValid = false;
        }
        if (username.isEmpty()) {
            jLabelUser.setText("Polje korisnicko ime ne može biti prazno!");
            isValid = false;
        }
       // if (pass.isEmpty()) {
       //     jLabelPass.setText("Lozinka ne može biti prazna!");
       //     isValid = false;
       // }
       if(port.isEmpty()){
           jLabelPort.setText("Polje port ne moze biti prazno!");
       }
        if (!port.matches("^\\d+$") || Integer.parseInt(port) < 1 || Integer.parseInt(port) > 65535) {
            jLabelPort.setText("Port mora biti između 1 i 65535!");
            isValid = false;
        }
        return isValid;
    }

    private void fillFields() {
        jTextFieldPort.setText(config.getProperty("port"));
        jTextFieldURL.setText(config.getProperty("db_url"));
        jTextFieldUser.setText(config.getProperty("db_user"));
        jPasswordField.setText(config.getProperty("db_password"));
    }

    private void setFieldsEnabled(boolean b) {
        jTextFieldURL.setEnabled(b);
        jTextFieldPort.setEnabled(b);
        jTextFieldUser.setEnabled(b);
        jPasswordField.setEnabled(b);
        jButtonSave.setEnabled(b);
    }
}
